AUTHORS.md, README.md
* Added an AUTHORS.md file
* Got rid of that ugly CLA stuff
Fixes #2
=> Updated contributing section

examples/unwrapped/create_template.php, lib/SparkPost/APIResource.php, lib/SparkPost/SparkPost.php, lib/SparkPost/Transmission.php, test/unit/APIResourceTest.php, test/unit/SparkPostTest.php, test/unit/TransmissionTest.php
Here is a re-factored version of the SDK that I wrote.
The new base object APIResource can be easily extended and modeled for various endpoints, or used directly on any unwrapped endpoints (see provided example).
I will admit I'm pushing these changes a bit prematurely, but I am out of town for a week so I tried to quickly clean it up and get it out before I left. It has NOT been tested, outside of the unit tests. Once I get back I will continue development.
=> SDK Refactor for easy extensibility

.gitignore, README.md, composer.json, composer.lock, examples/transmission/get_all_transmissions.php, examples/transmission/get_transmission.php, examples/transmission/rfc822.php, examples/transmission/send_transmission_all_fields.php, examples/transmission/simple_send.php, examples/transmission/stored_recipients_inline_content.php, examples/transmission/stored_template_send.php, examples/unwrapped/create_template.php
=> Example config

.gitignore, composer.json, lib/SendGridCompatibility/Email.php, lib/SendGridCompatibility/SendGrid.php, lib/SparkPost/APIResource.php, lib/SparkPost/APIResponseException.php, lib/SparkPost/SparkPost.php, lib/SparkPost/Transmission.php, test/unit/SparkPostTest.php
Also one test is removed, because my opinion is that strong-typing is better than condition with 'instanceof', especially in cases when it is a simple check for only one class.
And for strong-typing we don't need tests, because it's like test for builtin php functionality, what is already tested.
Also I removed @desc tag, because phpDoc doesn't have that tag implemented and it does nothing.
Also I make code following PSR-2 standard, but if you don't like that, I can return all those braces, that are now on the next line.
=> Fixed namespaces, cleaned code/comments

README.md
People are expressing concern and confusion around the deprecated Ivory package, but it's not actually a big deal and won't have an effect on them now or in the future. Just adding a note to our README to explain that briefly.
=> Adding Ivory note to README

lib/SparkPost/Transmission.php
Additional mapping in `Transmission::$parameterMappings` to support attachments.
=> Support attachments

README.md
A quick doc update to clarify the optionality of 'from' when a template is used.
=> docs - identify from as optional when a template is in use

lib/SparkPost/APIResource.php, lib/SparkPost/APIResponseException.php, test/unit/APIResourceExceptionTest.php, test/unit/APIResourceTest.php
Hi
I work on SparkPost module for Drupal. I had some troubles sending email and Exception message and Code doesn't really help to investigate what was the source of the problem. API response has quite nice error message handling so I've added arguments to APIResponseException definition to aggregate API error messages.
`__construct($message = "", $code = 0, $apiMessage = "", $apiCode = 0, $apiMessageDescription = "")`
where
`$message` is custom message, 
`$code` is HTTP status Code,
`$apiMessage` is API error message received from endpoint,
`$apiCode` is API error code received from endpoint, 
`$apiMessageDescription` is API error message description received from endpoint.
Nothing special but it should improve DX, fix #44 and is backward compatible.
=> Improve APIResponseException class

lib/SparkPost/APIResource.php, test/unit/APIResourceTest.php
=> Improve Exception message on 403 response

.gitignore, AUTHORS.md, CHANGELOG.md, lib/SparkPost/APIResource.php, lib/SparkPost/MessageEvent.php, lib/SparkPost/MessageEvents.php, lib/SparkPost/SparkPost.php, lib/SparkPost/Transmission.php, test/unit/APIResourceTest.php, test/unit/MessageEventTest.php, test/unit/TransmissionTest.php
I've implemented the Message Events functionality, trying to keep to the same style of unit tests etc.  There are a couple of points of note/ for discussion:
1. The Message Events API accepts a comma-separated list of values for each query parameter.  Given that it's potentially used elsewhere in the API, I added the implosion of an array query parameter in the base APIResource class (and augmented the unit tests to cover it).
2. For some reason the Message Events API takes a date-time in a different format to the Transmission API (without seconds or UTC offset).  Rather than making the user mess with formatting these differently for each API call I added code to format a passed-in `\DateTime` object in each scenario.
3. I've run manual integration tests against my own API key.  I'm a bit …
=> Message Events

composer.json, lib/SparkPost/SparkPost.php
- Some users don't use composer and the code required the composer.json
- Resolves #95
=> Remove reliance on composer

examples/transmission/delete_transmission.php, examples/transmission/get_all_transmissions.php, examples/transmission/get_transmission.php, examples/transmission/rfc822.php, examples/transmission/send_transmission_all_fields.php, examples/transmission/simple_send.php, examples/transmission/stored_recipients_inline_content.php, examples/transmission/stored_template_send.php, lib/SparkPost/APIResource.php, test/unit/APIResourceTest.php
- Update to return message, code, and description from API (if available, with fallback) (thanks @zaporylie!)
- Update examples to use use extra methods available on the SparkPost exception class
- Fixes #83
=> Return extended exception data

.editorconfig, CONTRIBUTING.md, composer.json, composer.lock, examples/bootstrap.php, examples/transmission/delete_transmission.php, examples/transmission/get_all_transmissions.php, examples/transmission/get_transmission.php, examples/transmission/rfc822.php, examples/transmission/send_transmission_all_fields.php, examples/transmission/simple_send.php, examples/transmission/stored_recipients_inline_content.php, examples/transmission/stored_template_send.php, examples/unwrapped/create_template.php, examples/unwrapped/get_webhooks.php, lib/SendGridCompatibility/Email.php, lib/SendGridCompatibility/SendGrid.php, lib/SparkPost/APIResource.php, lib/SparkPost/APIResponseException.php, lib/SparkPost/MessageEvents.php, lib/SparkPost/SparkPost.php, lib/SparkPost/Transmission.php, test/unit/APIResourceExceptionTest.php, test/unit/APIResourceTest.php, test/unit/MessageEventTest.php, test/unit/SendGridCompatibiility/EmailTest.php, test/unit/SparkPostTest.php, test/unit/TestUtils/ClassUtils.php, test/unit/TransmissionTest.php, test/unit/bootstrap.php
Let's get a few eyes on this to make sure it looks ok, but this will make style stuff way easier imo.
=> Add php-cs-fixer as composer script and make initial fix-style run

examples/transmission/send_with_bcc.php, examples/transmission/send_with_cc.php
To test:
* Clone repo, cd into repo folder
* Run `composer install`
* `cd examples`
* edit `example-config.json`, adding your API key
* edit the example files to use real emails
* run `php -f transmissions/send_with_cc.php`
* run `php -f transmissions/send_with_bcc.php`
=> FAD-3045 add examples for cc/bcc

examples/transmission/send_transmission_all_fields.php, lib/SparkPost/SparkPost.php
Added an option to overwrite the default 10 seconds timeout with any value. 
Please note I suggest we allow for an entire guzzle configuration to be passed in, as the current method of overwriting the configuration in the Sparkpost class brings confusion as the guzzle configurations that are passed into the wrapper originally are overwritten.
Fixes #106 , #107 , #109 
Please note there is an extra parameter that you can now pass into the sparkpost config array that looks like this:
`['key' => $config['api-key'], 'timeout' => 0]]`
=> Added an option to overwrite the default 10 seconds timeout

lib/SparkPost/Transmission.php
Hello !
Thanks for the 2.0 update, it makes a lot of sense, and removes the deprecated Ivory dependency, so good ! :+1: 
Unfortunately, at the moment, it seems like adding a `From` address is a hard requirement, even when using templates (which you can set up the `From` address for in the Sparkpost UI).
This fixes this use case. I didn't dive to deep into the details : maybe there should be some additional checks in case we are *not* using a template, in which case a `From` would indeed be needed.
Just wanted to get feedback first.
Best regards,
Conrad @ reassurez-moi.fr
=> Transmissions : makes "from" address optional for use with templates

composer.json, composer.lock, lib/SparkPost/SparkPost.php, test/unit/SparkPostTest.php, test/unit/TestUtils/ClassUtils.php, test/unit/TransmissionTest.php
Removed dependency from Guzzle. If we use php-http/discovery instead of guzzlehttp/psr7 we can let the user decide what implementation to use. 
I also did some code cleanup and make sure someone can add a async client.
=> Remove dependency form Guzzle

examples/message-events/get_message_events.php, examples/templates/create_template.php, examples/templates/delete_template.php, examples/templates/get_all_templates.php, examples/templates/get_template.php, examples/templates/preview_template.php, examples/templates/update_template.php, examples/transmissions/create_transmission_with_recipient_list.php, examples/transmissions/create_transmission_with_template.php, examples/transmissions/get_transmission.php, lib/SparkPost/Transmission.php, test/unit/TransmissionTest.php
Fixed sending with recipient lists
Added template and recipient list examples
=> Updating examples

.coveralls.yml, composer.json, composer.lock, phpunit.xml.dist
This PR adds satooshi/php-coveralls back to composer.json.
=> Fix #152: Coveralls integration does not work

lib/SparkPost/SparkPost.php
We should return current object from all setters to make them compatible with [fluent interface](https://en.wikipedia.org/wiki/Fluent_interface) (allow chaining).
=> Setters should return current object.

README.md, examples/message-events/get_message_events_with_retry_logic.php, lib/SparkPost/SparkPost.php, test/unit/SparkPostTest.php
Addresses #168:
- Added a `retries` option to control API call retry count
- By default, no retries are attempted to protect existing tested code paths and compatibility
- When enabled, each request will be retried until it returns non 5xx status or `retries` attempts are reached.
=> Issue-168: Optional automatic retry on 5xx

README.md
Current async example makes assumption that the promise will be resolved somewhere in the code later, but for newbies to this concept it's not clear.
=> Make promises usage more explicit

CHANGELOG.md, README.md, lib/SparkPost/SparkPost.php
Removed the formfeed replacement code. Confirmed that the error reported in #197 is no longer seen, and that the email is sent as expected.
Updated the main README example (as it was broken). Needs the async option setting to make it work. Added try { } clause as good practice, and made it print out the response results too.
I also added some //TODO comments next to the transmissions->get call that will not work.
=> Address #197: No longer need formfeed replacement. README work.
